### ISSUE TITLE
Manage unique children on workflow - None and prompt

### ISSUE THREAD

**Issue by RafaelGB** [RafaelGB/Obsidian-ZettlelFlow#5]

**Comment by RafaelGB** [comment]
Prompt section working correctly adding a new key to the frontmatter in function of
```yaml
zettelFlowSettings:
  label: 'Purpose'
  element:
    type: 'prompt'
    placeholder: 'Purpose of your note'
    key: 'purpose'
```

![Image](https://github.com/RafaelGB/Obsidian-ZettlelFlow/assets/11924043/bb2d21ce-b1e9-4449-9ceb-be57e6acb12d)



![Image](https://github.com/RafaelGB/Obsidian-ZettlelFlow/assets/11924043/727133c2-1b58-4683-ab61-559686203bfb)
